---
- name: Automate the aws os pacthing activity
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'
    resources_grp: "{{ resources_grp_name }}"
    mw_nm: "{{ mw_name }}"
    

  tasks:
    - name: Create maintenance window for aws OS patching     
      shell: |            
        {{ aws_cli_path }}  ssm create-maintenance-window \
            --name "MW_WIN_Testable" \
            --schedule 'rate(5 minutes)' \
            --duration 2 \
            --cutoff 1 \
            --allow-unassociated-targets                            
      register: mv_output    
  
    - name: Get the mv_output from output
      set_fact:
        mw_id: "{{ mv_output.stdout | from_json | json_query('WindowId')}}"
        
    - name: DISPLAY aurora_cluster
      debug:
        var: mw_id
              
  