---
- name: Print version
  debug:
    msg: "System {{ inventory_hostname }} have uuid {{ ansible_product_uuid }}"
- name: Check connectivity to remote servers
  hosts: all #servergroup01  
  tasks:
    - name: ping
      ping: