---
- name: Check connectivity to remote servers
  hosts: tag_Name_TestableLinx 

  vars:
    test_variable: "my test variable"

  tasks:
    - name: DISPLAY TEST_VARIABLE
      debug:
        var: test_variable
  tasks:
    - name: ping     
      ping: