---
- name: Check connectivity to remote servers
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'

  tasks:
    - name: DISPLAY TEST_VARIABLE
      shell: "{{ aws_cli_path }} --version"  
      shell: |
        {{ aws_cli_path }} resource-groups update-group \
            --region "us-east-1" \
            --group-name "RG_Win_Testable" \
            --description "Group of win EC2 testable instances"
      register: res_query     
   
  
    - name: DISPLAY TEST_VARIABLE
      debug:
        var: res_query
        
    
    - name: parse the response and check if our Aurora cluster is there
      set_fact:
        aurora_cluster: "{{ aurora_cluster_query.stdout | from_json | json_query('Group[1]')}}"
        
    - name: DISPLAY aurora_cluster
      debug:
        var: aurora_cluster
              
  