---
- name: Check connectivity to remote servers
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'

  tasks:
    - name: DISPLAY TEST_VARIABLE
      shell: "{{ aws_cli_path }} --version"  
      shell: |
        {{ aws_cli_path }} resource-groups update-group \
            --region "us-east-1" \
            --group-name "RG_Win_Testable" \
            --description "Group of win EC2 testable instances"
            
   
  tasks:
    - name: DISPLAY TEST_VARIABLE
      debug:
        var: aws_cli_path
            
  