---
- name: Check connectivity to remote servers
  hosts: tag_Name_TestableLinx 

  vars:
    aws_cli_path: '/usr/local/bin/aws'

  tasks:
    - name: DISPLAY TEST_VARIABLE
      shell: "{{ aws_cli_path }} --version"        
  