---
- name: Check connectivity to remote servers
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'

  tasks:
    - name: DISPLAY TEST_VARIABLE
      shell: "{{ aws_cli_path }} --version"  
      shell: |
        {{ aws_cli_path }} resource-groups update-group \
            --group-name "RG_Win_Teastable" \
            --description "Group of win EC2 testable instances"
            
  