---
- name: Check connectivity to remote servers
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'
    name_var: "{{ name }}"
    last_var: "{{ last }}"

  tasks:
    - name: DISPLAY TEST_VARIABLE
      shell: "{{ aws_cli_path }}" --version         
    
    - name: DISPLAY TEST_VARIABLE
      debug:
        var: aws_cli_path
    