---
- name: Automate the aws os pacthing activity
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'
    resources_grp: "{{ resources_grp_name }}"
    mw_nm: "{{ mw_name }}" 
    operation: "{{ Operation }}" 

    tasks:
    - name: Create resource-groups and register the created group name     
      debug:
        msg: "Create resource-groups"
      when: operation == "Create"
  
    - name: Create resource-groups and register the created group name     
      debug:
         msg: "Update resource-groups"
      when: operation == "Update"

    - name: Create resource-groups and register the created group name     
      debug:
         msg: "Delete resource-groups"
      when: operation == "Delete"