---
- name: Automate the aws os pacth activity
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'
    resources_grp: "{{ Name }}"
    mw_nm: "{{ mw_name }}" 
    operation: "{{ Operation }}" 

  tasks:
    - name: DISPLAY Operation
      debug:
        var: Description
        var: ResourceQuery

    - name: Create resource-groups and register the created group name     
      shell: |            
        {{ aws_cli_path }} resource-groups create-group \            
            --name {{ Name }} \
            --description {{ Description }} \
            --resource-query '{"Type":"{{ ResourceQuery.Type }}","Query":"{\"ResourceTypeFilters\":[\"AWS::EC2::Instance\"],\"TagFilters\":[{\"Key\":\"PatchGroup\",\"Values\":[\"TestableWinGrp\"]}]}"}'      
      register: resource_groups_output
      when: operation == "Create"
     

    - name: Update resource-groups and register the created group name     
      shell: |            
        {{ aws_cli_path }} resource-groups update-group \  
            --group-name {{ GroupName }} \
            --description {{ Description }} 

      when: operation == "Update"

    - name: Delete resource-groups and register the created group name     
      shell: |            
        {{ aws_cli_path }} resource-groups delete-group \
            --group-name {{ GroupName }}
      
      when: operation == "Delete"
