---
- name: Automate the aws os pacth activity
  hosts: tag_Name_ict_provisioner 

  vars:
    aws_cli_path: '/usr/bin/aws'
    resources_grp: "{{ Name }}"
    mw_nm: "{{ mw_name }}" 
    operation: "{{ Operation }}" 
    query1: "{\"ResourceTypeFilters\":[\"AWS::EC2::Instance\"],\"TagFilters\":[{\"Key\":\"PatchGroup\",\"Values\":[\"TestableWinGrp\"]}]}"
    query: '{"ResourceTypeFilters":["AWS::EC2::Instance"],"TagFilters":[{"Key":"PatchGroup","Values":["TestableWinGrp"]}]}'
    query2: '{{ query | to_json  }}'
  tasks:
    - name: DISPLAY Operation
      debug:
        var: Description
        var: query
        var: query2

    - name: Create resource-groups and register the created group name     
      shell: |            
        {{ aws_cli_path }} resource-groups create-group \            
            --name {{ Name }} \
            --description {{ Description }} \
            --resource-query '{"Type":"TAG_FILTERS_1_0","Query": {{ query2 }} }'     
      register: resource_groups_output
      when: operation == "Create"
     

    - name: Update resource-groups and register the created group name     
      shell: |            
        {{ aws_cli_path }} resource-groups update-group \  
            --group-name {{ GroupName }} \
            --description {{ Description }} 

      when: operation == "Update"

    - name: Delete resource-groups and register the created group name     
      shell: |            
        {{ aws_cli_path }} resource-groups delete-group \
            --group-name {{ GroupName }}
      
      when: operation == "Delete"
